### ISSUE TITLE
Test against recent standard with array-api-test suite

### ISSUE THREAD

**Issue by cbourjau** [Quantco/ndonnx#31]
The upstream test suite allows for [setting](https://github.com/data-apis/array-api-tests?tab=readme-ov-file#specifying-the-api-version) a particular target version. If not set, it defaults to  `2021.12`, which is much older than what we are striving for.

**Comment by adityagoel4512** [comment]
Closed in https://github.com/Quantco/ndonnx/pull/37 (with some room for improvement)
