### ISSUE TITLE
Promotion of Python scalars is losing precission

### ISSUE THREAD

**Issue by cbourjau** [Quantco/ndonnx#38]
Type promotion currently tries to be smart by seemingly finding the [smallest fitting data type](https://github.com/Quantco/ndonnx/blob/634442344b577c3028e2819fde66612add0af4ff/ndonnx/_utility.py#L49). Unfortunately, this does not appear to be working as intended. The consequence is that we lose precision on Python scalars during the type promotion. The following tests case demonstrates the issue:

```python
def test_promote(val, strict):
    promoted, = ndx._utility.promote(val)
    promoted_np = promoted.to_numpy()

    np.testing.assert_equal(np.asarray(val), promoted_np, strict=strict)

test_promote(0.123456789, strict=False)
```
which fails with:
```
AssertionError: 
Arrays are not equal

Mismatched elements: 1 [/](http://localhost:8888/) 1 (100%)
Max absolute difference among violations: 2.04328156e-09
Max relative difference among violations: 1.65505805e-08
 ACTUAL: array(0.123457)
 DESIRED: array(0.123457, dtype=float32)
```
I.e., `0.123456789` has been demoted to a float32 in ndonnx while it was kept as a float64 in NumPy. The demotion did cost significant loss in precision.

**Comment by adityagoel4512** [comment]
More context: https://github.com/numpy/numpy/issues/8207
